--- 
development: 
  adapter: postgresql
  username: 
  host: 
  database: 
  password: 
test: 
  adapter: postgresql
  username: 
  host: 
  database: 
  password: 
production: 
  adapter: postgresql
  username:
  host:
  database:
  password:
