--- 
development: 
  adapter: postgresql
  username: app17518
  host: 10.252.154.195
  database: app17518
  password: pvLvAHh.cT%fsNSpcti
test: 
  adapter: postgresql
  username: test_app17518
  host: 10.252.154.195
  database: test_app17518
  password: VhzXVH,kE+4
production: development
