--- 
development: 
  adapter: postgresql
  username: app17518
  host: 10.252.154.195
  database: app17518
  password: DG=bW3@n5v2%
test: 
  adapter: postgresql
  username: test_app17518
  host: 10.252.154.195
  database: test_app17518
  password: uKlBbSc-eVg8
production: development
